services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    build: . # TODO: replace with image again
    ports:
      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - MEILI_HOST=http://archivist-meilisearch:7700
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=http://localhost:3000 # set your host name with protocol and port
      - TA_USERNAME=tubearchivist # your initial TA credentials
      - TA_PASSWORD=verysecret # your initial TA credentials
      - MEILI_MASTER_KEY=verysecretmeilikey # set a strong master key for Meilisearch
      - TZ=America/New_York # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-meilisearch
      - archivist-redis
  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-meilisearch
  archivist-meilisearch:
    image: getmeili/meilisearch:latest
    container_name: archivist-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=verysecretmeilikey # must match MEILI_MASTER_KEY above
      - MEILI_ENV=production
    volumes:
      - meilisearch:/meili_data
    ports:
      - 7700:7700

volumes:
  media:
  cache:
  redis:
  meilisearch:
